"use server";
import { createClient } from "../supabase/server";
import { redirect } from "next/navigation";
const fetch_event_types = async () => {
  const supabase = await createClient();
  try {
    const { data, error } = await supabase
      .from("event_type")
      .select("*")
      .neq("name", "AutoGenerated");

    if (error) {
      throw new Error(`Failed to fetch event types: ${error.message}`);
    }

    return data;
  } catch (error) {
    redirect("/error");
  }
};

export default fetch_event_types;
