import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "ClassPlan",
  description: "Generated by create next app",
  icons: {
    icon: "/ClassPlanIcon.ico",
  },
};
import { AILoadingProvider } from "@/components/AiLoadingContext";

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <head>
        <script src="https://accounts.google.com/gsi/client" async></script>
      </head>
      <body>
        <AILoadingProvider>{children}</AILoadingProvider>
      </body>
    </html>
  );
}
