import type { Metadata } from "next";
import { AILoadingProvider } from "@/components/AiLoadingContext";

export const metadata: Metadata = {
  title: "ClassPlan",
  description: "Generated by create next app",
  icons: {
    icon: "/ClassPlanIcon.ico",
  },
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <head>
        <script src="https://accounts.google.com/gsi/client" async></script>
      </head>
      <body>
        <AILoadingProvider>{children}</AILoadingProvider>
      </body>
    </html>
  );
}
